export const initialFormData = {
  ShipmentDetails: {
    "Origin Country": "",
    "Destination Country": "",
    "HS Code": "",
    "Product Description": "",
    Quantity: "",
    "Gross Weight": "",
  },
  TradeAndRegulatoryDetails: {
    "Incoterms 2020": "",
    "Declared Value": { currency: "", amount: "" },
    "Currency of Transaction": "",
    "Trade Agreement Claimed": "",
    "Dual-Use Goods": "No",
    "Hazardous Material": "No",
    Perishable: "No",
  },
  PartiesAndIdentifiers: {
    "Shipper/Exporter": "",
    "Consignee/Importer": "",
    "Manufacturer Information": "",
    "EORI/Tax ID": "",
  },
  LogisticsAndHandling: {
    "Means of Transport": "",
    "Port of Loading": "",
    "Port of Discharge": "",
    "Special Handling": "",
    "Temperature Requirements": "",
  },
  DocumentVerification: {
    "Commercial Invoice": {
      checked: false,
      subItems: {
        "Invoice number present": false,
        "Details match shipment": false,
        "Customs compliant": false,
      },
    },
    "Packing List": {
      checked: false,
      subItems: {
        "Contents accurate": false,
        "Quantities match": false,
        "Matches invoice": false,
      },
    },
    "Certificate of Origin": {
      checked: false,
      subItems: {
        "Origin verified": false,
        "Trade agreement compliant": false,
      },
    },
    "Licenses/Permits": {
      checked: false,
      subItems: {
        "Valid number": false,
        "Not expired": false,
        "Authority verified": false,
      },
    },
    "Bill of Lading": {
      checked: false,
      subItems: {
        "Accurate details": false,
        "Shipping regulations compliant": false,
      },
    },
  },
  IntendedUseDetails: {
    "Intended Use": "",
  },
};

export const tabOrder = [
  "ShipmentDetails",
  "TradeAndRegulatoryDetails",
  "PartiesAndIdentifiers",
  "LogisticsAndHandling",
  "DocumentVerification",
  "IntendedUseDetails",
];

export const countryOptions = [
  { value: "AF", label: "Afghanistan" },
  { value: "AL", label: "Albania" },
  { value: "DZ", label: "Algeria" },
  { value: "AD", label: "Andorra" },
  { value: "AO", label: "Angola" },
  { value: "AG", label: "Antigua and Barbuda" },
  { value: "AR", label: "Argentina" },
  { value: "AM", label: "Armenia" },
  { value: "AU", label: "Australia" },
  { value: "AT", label: "Austria" },
  { value: "AZ", label: "Azerbaijan" },
  { value: "BS", label: "Bahamas" },
  { value: "BH", label: "Bahrain" },
  { value: "BD", label: "Bangladesh" },
  { value: "BB", label: "Barbados" },
  { value: "BY", label: "Belarus" },
  { value: "BE", label: "Belgium" },
  { value: "BZ", label: "Belize" },
  { value: "BJ", label: "Benin" },
  { value: "BT", label: "Bhutan" },
  { value: "BO", label: "Bolivia" },
  { value: "BA", label: "Bosnia and Herzegovina" },
  { value: "BW", label: "Botswana" },
  { value: "BR", label: "Brazil" },
  { value: "BN", label: "Brunei" },
  { value: "BG", label: "Bulgaria" },
  { value: "BF", label: "Burkina Faso" },
  { value: "BI", label: "Burundi" },
  { value: "CV", label: "Cabo Verde" },
  { value: "KH", label: "Cambodia" },
  { value: "CM", label: "Cameroon" },
  { value: "CA", label: "Canada" },
  { value: "CF", label: "Central African Republic" },
  { value: "TD", label: "Chad" },
  { value: "CL", label: "Chile" },
  { value: "CN", label: "China" },
  { value: "CO", label: "Colombia" },
  { value: "KM", label: "Comoros" },
  { value: "CD", label: "Congo (DRC)" }, // Democratic Republic of the Congo
  { value: "CG", label: "Congo (Republic)" }, // Republic of the Congo
  { value: "CR", label: "Costa Rica" },
  { value: "CI", label: "Côte d'Ivoire" },
  { value: "HR", label: "Croatia" },
  { value: "CU", label: "Cuba" },
  { value: "CY", label: "Cyprus" },
  { value: "CZ", label: "Czechia" }, // Czech Republic
  { value: "DK", label: "Denmark" },
  { value: "DJ", label: "Djibouti" },
  { value: "DM", label: "Dominica" },
  { value: "DO", label: "Dominican Republic" },
  { value: "EC", label: "Ecuador" },
  { value: "EG", label: "Egypt" },
  { value: "SV", label: "El Salvador" },
  { value: "GQ", label: "Equatorial Guinea" },
  { value: "ER", label: "Eritrea" },
  { value: "EE", label: "Estonia" },
  { value: "SZ", label: "Eswatini" }, // Swaziland
  { value: "ET", label: "Ethiopia" },
  { value: "FJ", label: "Fiji" },
  { value: "FI", label: "Finland" },
  { value: "FR", label: "France" },
  { value: "GA", label: "Gabon" },
  { value: "GM", label: "Gambia" },
  { value: "GE", label: "Georgia" },
  { value: "DE", label: "Germany" },
  { value: "GH", label: "Ghana" },
  { value: "GR", label: "Greece" },
  { value: "GD", label: "Grenada" },
  { value: "GT", label: "Guatemala" },
  { value: "GN", label: "Guinea" },
  { value: "GW", label: "Guinea-Bissau" },
  { value: "GY", label: "Guyana" },
  { value: "HT", label: "Haiti" },
  { value: "HN", label: "Honduras" },
  { value: "HU", label: "Hungary" },
  { value: "IS", label: "Iceland" },
  { value: "IN", label: "India" },
  { value: "ID", label: "Indonesia" },
  { value: "IR", label: "Iran" },
  { value: "IQ", label: "Iraq" },
  { value: "IE", label: "Ireland" },
  { value: "IL", label: "Israel" },
  { value: "IT", label: "Italy" },
  { value: "JM", label: "Jamaica" },
  { value: "JP", label: "Japan" },
  { value: "JO", label: "Jordan" },
  { value: "KZ", label: "Kazakhstan" },
  { value: "KE", label: "Kenya" },
  { value: "KI", label: "Kiribati" },
  { value: "KP", label: "North Korea" },
  { value: "KR", label: "South Korea" },
  { value: "XK", label: "Kosovo" }, // Often included, though status is disputed
  { value: "KW", label: "Kuwait" },
  { value: "KG", label: "Kyrgyzstan" },
  { value: "LA", label: "Laos" },
  { value: "LV", label: "Latvia" },
  { value: "LB", label: "Lebanon" },
  { value: "LS", label: "Lesotho" },
  { value: "LR", label: "Liberia" },
  { value: "LY", label: "Libya" },
  { value: "LI", label: "Liechtenstein" },
  { value: "LT", label: "Lithuania" },
  { value: "LU", label: "Luxembourg" },
  { value: "MG", label: "Madagascar" },
  { value: "MW", label: "Malawi" },
  { value: "MY", label: "Malaysia" },
  { value: "MV", label: "Maldives" },
  { value: "ML", label: "Mali" },
  { value: "MT", label: "Malta" },
  { value: "MH", label: "Marshall Islands" },
  { value: "MR", label: "Mauritania" },
  { value: "MU", label: "Mauritius" },
  { value: "MX", label: "Mexico" },
  { value: "FM", label: "Micronesia" },
  { value: "MD", label: "Moldova" },
  { value: "MC", label: "Monaco" },
  { value: "MN", label: "Mongolia" },
  { value: "ME", label: "Montenegro" },
  { value: "MA", label: "Morocco" },
  { value: "MZ", label: "Mozambique" },
  { value: "MM", label: "Myanmar" }, // Burma
  { value: "NA", label: "Namibia" },
  { value: "NR", label: "Nauru" },
  { value: "NP", label: "Nepal" },
  { value: "NL", label: "Netherlands" },
  { value: "NZ", label: "New Zealand" },
  { value: "NI", label: "Nicaragua" },
  { value: "NE", label: "Niger" },
  { value: "NG", label: "Nigeria" },
  { value: "MK", label: "North Macedonia" },
  { value: "NO", label: "Norway" },
  { value: "OM", label: "Oman" },
  { value: "PK", label: "Pakistan" },
  { value: "PW", label: "Palau" },
  { value: "PS", label: "Palestine" }, // State of Palestine
  { value: "PA", label: "Panama" },
  { value: "PG", label: "Papua New Guinea" },
  { value: "PY", label: "Paraguay" },
  { value: "PE", label: "Peru" },
  { value: "PH", label: "Philippines" },
  { value: "PL", label: "Poland" },
  { value: "PT", label: "Portugal" },
  { value: "QA", label: "Qatar" },
  { value: "RO", label: "Romania" },
  { value: "RU", label: "Russia" },
  { value: "RW", label: "Rwanda" },
  { value: "KN", label: "Saint Kitts and Nevis" },
  { value: "LC", label: "Saint Lucia" },
  { value: "VC", label: "Saint Vincent and the Grenadines" },
  { value: "WS", label: "Samoa" },
  { value: "SM", label: "San Marino" },
  { value: "ST", label: "Sao Tome and Principe" },
  { value: "SA", label: "Saudi Arabia" },
  { value: "SN", label: "Senegal" },
  { value: "RS", label: "Serbia" },
  { value: "SC", label: "Seychelles" },
  { value: "SL", label: "Sierra Leone" },
  { value: "SG", label: "Singapore" },
  { value: "SK", label: "Slovakia" },
  { value: "SI", label: "Slovenia" },
  { value: "SB", label: "Solomon Islands" },
  { value: "SO", label: "Somalia" },
  { value: "ZA", label: "South Africa" },
  { value: "SS", label: "South Sudan" },
  { value: "ES", label: "Spain" },
  { value: "LK", label: "Sri Lanka" },
  { value: "SD", label: "Sudan" },
  { value: "SR", label: "Suriname" },
  { value: "SE", label: "Sweden" },
  { value: "CH", label: "Switzerland" },
  { value: "SY", label: "Syria" },
  { value: "TW", label: "Taiwan" }, // Often included, though political status is disputed
  { value: "TJ", label: "Tajikistan" },
  { value: "TZ", label: "Tanzania" },
  { value: "TH", label: "Thailand" },
  { value: "TL", label: "Timor-Leste" }, // East Timor
  { value: "TG", label: "Togo" },
  { value: "TO", label: "Tonga" },
  { value: "TT", label: "Trinidad and Tobago" },
  { value: "TN", label: "Tunisia" },
  { value: "TR", label: "Turkey" },
  { value: "TM", label: "Turkmenistan" },
  { value: "TV", label: "Tuvalu" },
  { value: "UG", label: "Uganda" },
  { value: "UA", label: "Ukraine" },
  { value: "AE", label: "United Arab Emirates" },
  { value: "GB", label: "United Kingdom" },
  { value: "US", label: "United States" },
  { value: "UY", label: "Uruguay" },
  { value: "UZ", label: "Uzbekistan" },
  { value: "VU", label: "Vanuatu" },
  { value: "VA", label: "Vatican City" },
  { value: "VE", label: "Venezuela" },
  { value: "VN", label: "Vietnam" },
  { value: "YE", label: "Yemen" },
  { value: "ZM", label: "Zambia" },
  { value: "ZW", label: "Zimbabwe" },
];

export const incotermsOptions = [
  { value: "EXW", label: "EXW" },
  { value: "FOB", label: "FOB" },
  { value: "CIF", label: "CIF" },
];

export const currencyOptions = [
  { value: "USD", label: "USD" },
  { value: "EUR", label: "EUR" },
  { value: "GBP", label: "GBP" },
];

export const booleanOptions = [
  { value: "Yes", label: "Yes" },
  { value: "No", label: "No" },
];

export const transportOptions = [
  { value: "Sea", label: "Sea" },
  { value: "Air", label: "Air" },
  { value: "Road", label: "Road" },
];

export const formStructure = {
  ShipmentDetails: [
    {
      field: "Origin Country",
      type: "Categorical",
      why_checked:
        "Determines export/import regulations, trade agreements, and restrictions.",
      option_type: "Dropdown (ISO 3166-1 alpha-2)",
      mandatory: true,
    },
    {
      field: "Destination Country",
      type: "Categorical",
      why_checked:
        "Identifies import regulations, duties, prohibited goods, and required documentation.",
      option_type: "Dropdown (ISO 3166-1 alpha-2)",
      mandatory: true,
    },
    {
      field: "HS Code",
      type: "Numeric",
      why_checked:
        "Essential for tariff classification, import duties, trade statistics, and product regulations.",
      option_type: "Number input",
      mandatory: true,
      placeholder: "e.g., 12345678",
    },
    {
      field: "Product Description",
      type: "Text",
      why_checked:
        "Verifies HS Code, identifies restricted items, assesses safety, and determines handling/documentation needs.",
      option_type: "Text area",
      mandatory: true,
      placeholder: "e.g., Woven cotton fabric, Electronic components",
    },
    {
      field: "Quantity",
      type: "Numeric",
      why_checked:
        "Needed for customs valuation, duty calculation, inventory control, and document verification.",
      option_type: "Number input",
      mandatory: true,
      placeholder: "e.g., 100, 2500",
    },
    {
      field: "Gross Weight",
      type: "Numeric",
      why_checked:
        "Used for shipping costs, transportation requirements, and compliance with weight restrictions.",
      option_type: "Number input",
      mandatory: true,
      placeholder: "e.g., 50.5 (kg), 110 (lbs)",
    },
  ],
  TradeAndRegulatoryDetails: [
    {
      field: "Incoterms 2020",
      type: "Categorical",
      why_checked:
        "Defines responsibilities for costs, risks, and documentation in international trade.",
      option_type: "Dropdown",
      mandatory: true,
    },
    {
      field: "Declared Value",
      type: "Alphanumeric & Numeric",
      why_checked:
        "Used for calculating import duties/taxes, insurance, and customs valuation.",
      option_type: "Text input (Currency) & Number input (Amount)",
      mandatory: true,
      placeholder: "e.g., USD 1000.00",
    },
    {
      field: "Currency of Transaction",
      type: "Categorical",
      why_checked:
        "Relevant for financial compliance, currency exchange, and customs valuation.",
      option_type: "Dropdown",
      mandatory: true,
    },
    {
      field: "Trade Agreement Claimed",
      type: "Text",
      why_checked:
        "Determines eligibility for preferential duty treatment; requires specific documentation.",
      option_type: "Text input",
      mandatory: false,
      placeholder: "e.g., NAFTA, USMCA",
    },
    {
      field: "Dual-Use Goods",
      type: "Boolean",
      why_checked:
        "Subject to export controls and licensing due to potential military applications.",
      option_type: "Dropdown (Yes/No)",
      mandatory: false,
    },
    {
      field: "Hazardous Material",
      type: "Boolean",
      why_checked:
        "Subject to regulations for packaging, labeling, transportation, and documentation to ensure safety.",
      option_type: "Dropdown (Yes/No)",
      mandatory: false,
    },
    {
      field: "Perishable",
      type: "Boolean",
      why_checked:
        "Determines if special handling and temperature control are required.",
      option_type: "Dropdown (Yes/No)",
      mandatory: true,
    },
  ],
  PartiesAndIdentifiers: [
    {
      field: "Shipper/Exporter",
      type: "Text",
      why_checked:
        "Relevant for export regulations, documentation, and communication.",
      option_type: "Text input",
      mandatory: false,
      placeholder: "e.g., ABC Company Inc.",
    },
    {
      field: "Consignee/Importer",
      type: "Text",
      why_checked:
        "Relevant for import regulations, delivery arrangements, and communication.",
      option_type: "Text input",
      mandatory: false,
      placeholder: "e.g., XYZ Corporation",
    },
    {
      field: "Manufacturer Information",
      type: "Text",
      why_checked:
        "May be required for certificates of origin, product safety, and compliance.",
      option_type: "Text input",
      mandatory: false,
      placeholder: "e.g., Acme Manufacturing",
    },
    {
      field: "EORI/Tax ID",
      type: "Alphanumeric",
      why_checked:
        "Used for customs identification and tracking of economic operators.",
      option_type: "Text input",
      mandatory: false,
      placeholder: "e.g., EU1234567, 12-3456789",
    },
  ],
  LogisticsAndHandling: [
    {
      field: "Means of Transport",
      type: "Categorical",
      why_checked:
        "Affects regulations, documentation, and handling requirements.",
      option_type: "Dropdown",
      mandatory: true,
    },
    {
      field: "Port of Loading",
      type: "Text",
      why_checked:
        "Relevant for customs procedures, port regulations, and logistics.",
      option_type: "Text input",
      mandatory: false,
      placeholder: "e.g., Shanghai, Rotterdam",
    },
    {
      field: "Port of Discharge",
      type: "Text",
      why_checked:
        "Relevant for customs procedures, port regulations, and logistics.",
      option_type: "Text input",
      mandatory: false,
      placeholder: "e.g., Long Beach, Hamburg",
    },
    {
      field: "Special Handling",
      type: "Text",
      why_checked:
        "Ensures proper care during transport/storage, especially for fragile/sensitive items.",
      option_type: "Text area",
      mandatory: false,
      placeholder: "e.g., Fragile, Keep Dry",
    },
    {
      field: "Temperature Requirements",
      type: "Text",
      why_checked:
        "Critical for perishable/sensitive goods to maintain quality and safety.",
      option_type: "Text input",
      mandatory: false,
      placeholder: "e.g., 2-8°C, -10°F",
    },
  ],
  DocumentVerification: [
    {
      field: "Commercial Invoice",
      type: "Checkbox",
      why_checked:
        "Mandatory document for customs clearance; verifies transaction details.",
      option_type: "Checkbox",
      mandatory: true,
      placeholder: "Check if available",
      sub_items: [
        {
          field: "Invoice number present",
          type: "Checkbox",
          why_checked: "Verifies the presence of a unique invoice identifier.",
          option_type: "Checkbox",
          placeholder: "Check if present",
        },
        {
          field: "Details match shipment",
          type: "Checkbox",
          why_checked: "Ensures consistency with other shipment information.",
          option_type: "Checkbox",
          placeholder: "Check if details match",
        },
        {
          field: "Customs compliant",
          type: "Checkbox",
          why_checked: "Confirms the invoice meets customs requirements.",
          option_type: "Checkbox",
          placeholder: "Check if compliant",
        },
      ],
    },
    {
      field: "Packing List",
      type: "Checkbox",
      why_checked:
        "Mandatory document; details contents and quantities of the shipment.",
      option_type: "Checkbox",
      mandatory: true,
      placeholder: "Check if available",
      sub_items: [
        {
          field: "Contents accurate",
          type: "Checkbox",
          why_checked: "Verifies the accuracy of the listed contents.",
          option_type: "Checkbox",
          placeholder: "Check if accurate",
        },
        {
          field: "Quantities match",
          type: "Checkbox",
          why_checked:
            "Ensures quantities align with the invoice and other documents.",
          option_type: "Checkbox",
          placeholder: "Check if match",
        },
        {
          field: "Matches invoice",
          type: "Checkbox",
          why_checked: "Confirms consistency with the invoice.",
          option_type: "Checkbox",
          placeholder: "Check if matches",
        },
      ],
    },
    {
      field: "Certificate of Origin",
      type: "Checkbox",
      why_checked:
        "Verifies the country where the goods were produced; may be required for trade agreements.",
      option_type: "Checkbox",
      mandatory: false,
      placeholder: "Check if available",
      sub_items: [
        {
          field: "Origin verified",
          type: "Checkbox",
          why_checked: "Confirms the origin of the goods is verified.",
          option_type: "Checkbox",
          placeholder: "Check if verified",
        },
        {
          field: "Trade agreement compliant",
          type: "Checkbox",
          why_checked: "Checks compliance with trade agreement rules.",
          option_type: "Checkbox",
          placeholder: "Check if compliant",
        },
      ],
    },
    {
      field: "Licenses/Permits",
      type: "Checkbox",
      why_checked:
        "Verifies the presence of required licenses or permits for export/import.",
      option_type: "Checkbox",
      mandatory: false,
      placeholder: "Check if available",
      sub_items: [
        {
          field: "Valid number",
          type: "Checkbox",
          why_checked: "Checks if the license/permit number is valid.",
          option_type: "Checkbox",
          placeholder: "Check if valid",
        },
        {
          field: "Not expired",
          type: "Checkbox",
          why_checked: "Ensures the license/permit is not expired.",
          option_type: "Checkbox",
          placeholder: "Check if not expired",
        },
        {
          field: "Authority verified",
          type: "Checkbox",
          why_checked: "Verifies the issuing authority of the license/permit.",
          option_type: "Checkbox",
          placeholder: "Check if verified",
        },
      ],
    },
    {
      field: "Bill of Lading",
      type: "Checkbox",
      why_checked:
        "Mandatory document for sea transport; acts as a receipt for the goods.",
      option_type: "Checkbox",
      mandatory: false,
      placeholder: "Check if available",
      sub_items: [
        {
          field: "Accurate details",
          type: "Checkbox",
          why_checked:
            "Checks if the details on the bill of lading are accurate.",
          option_type: "Checkbox",
          placeholder: "Check if accurate",
        },
        {
          field: "Shipping regulations compliant",
          type: "Checkbox",
          why_checked: "Ensures compliance with shipping regulations.",
          option_type: "Checkbox",
          placeholder: "Check if compliant",
        },
      ],
    },
  ],
  IntendedUseDetails: [
    {
      field: "Intended Use",
      type: "Text",
      why_checked:
        "Relevant for regulatory compliance, product safety, and determining applicable standards.",
      option_type: "Text area",
      mandatory: false,
      placeholder: "e.g., Retail sale, Manufacturing use",
    },
  ],
};
